### ISSUE TITLE
Add note in semantics regarding proxies

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#1]
This is implied by the other points, but:
- GetValue and SetValue do not tunnel through proxies.
- Proxies do not trap private field access.

**Comment by erights** [comment]
How can this have observable consequences? When can it arise?

**Comment by zenparsing** [comment]
This was just a note for me to point out in the README something like the following:

``` js
class X {

    #a = 1;

    static hasA(obj) {
        try { obj.#a; return true; }
        catch (e) { return false; }
    }
}

let someX = new X();
let proxy = new Proxy(someX, {});
assert(X.hasA(someX) === true);
assert(X.hasA(proxy) === false);
```
