### ISSUE TITLE
Why not just use WeakMaps now?

### ISSUE THREAD

**Issue by doasync** [tc39/proposal-private-fields#103]
Check this out:
```
let internals = new WeakMap();

function $ (object) {
    !internals.has(object) && internals.set(object, {});
    return internals.get(object);
}

class MyClass {
  setPos(x, y) {
    $(this).x = x;
    $(this).y = y;
  }
  getPos() {
    const {x, y} = $(this);
    return {x, y};
  }
}
```
We also can use Proxy to make `this` instance available in private methods.

**Comment by bakkot** [comment]
This approach is [noted in the FAQ](https://github.com/tc39/proposal-private-fields/blob/master/FAQ.md#how-can-you-model-encapsulation-using-weakmaps), but it's widely considered to be non-obvious and unergonomic, and also there's some somewhat subtle ways to accidentally leak data you intended to be private (as also noted in the FAQ).
