### ISSUE TITLE
Protected fields

### ISSUE THREAD

**Issue by kobezzza** [tc39/proposal-private-fields#11]
What about protected fields, ie fields and methods can be used within a class and his children, but can't be used from the outside?

**Comment by zenparsing** [comment]
Protected fields might be a future extension.

Personally, I don't care to ever see protected access.

**Comment by indolering** [comment]
> Protected fields might be a future extension.

I'm worried that not addressing the protected API will lead to a less coherent syntax.

> Personally, I don't care to ever see protected access.

Really?  I'm working on a plugin system right now and I find myself grasping for a protected API.  Any essential readings on the topic?

**Comment by littledan** [comment]
See https://github.com/tc39/proposal-private-fields/blob/master/DECORATORS.md for discussion of how this proposal can extend to protected fields through use of decorators
