### ISSUE TITLE
Conflict with decorators?

### ISSUE THREAD

**Issue by lukescott** [tc39/proposal-private-fields#12]
Doesn't this conflict with https://github.com/wycats/javascript-decorators ?

What about something like this:

``` javascript
class Point {
    -x;
    -y;

    constructor(x = 0, y = 0) {
        this.x = +x;
        this.y = +y;
    }

    get x() { return this.x }
    set x(value) { this.x = +value }

    get y() { return this.y }
    set y(value) { this.y = +value }

    toString() { return `Point<${ this.x },${ this.y }>` }
}
```

The preceding `-` would indicate private. Would apply to methods as well. And then you would use the property like normal. A compiler like babel would just rename `x` and `y` to some semi-random key (seed based on hash of file?), like `__a3fe_x`, `__ce97_y`.

The example above with the getters/setters are for making sure a type stays a number. I put together a [proposal for type hinting here](https://github.com/lukescott/es-type-hinting) (need help!) that could make that example unnecessary. Private fields would still be _very_ useful though.

**Comment by zenparsing** [comment]
It does conflict with decorators, and finding an appropriate syntax that doesn't use `@` is quite a challenge.

Your suggestion has a bit of a problem:  when you execute the line:

``` js
this.x = +x;
```

Do you mean "access the private slot called `x` on object `this`", or "access the (normal) property `x` on object `this`"?  How is the engine supposed to know?

The `@` sigil was attractive for this reason.  In this example:

``` js
this.@x = +x;
```

It's explicitly clear that you are attempting to access an internal slot, as opposed to a regular property.

I've been letting this proposal sit while I try to find a suitable syntax that doesn't rely on `@`.  Suggestions welcome! : )

**Comment by lukescott** [comment]
I mean the (example in the first post) would desugar to:

``` javascript
class Point {
    __a3fe_x;
    __ce97_y;

    constructor(x = 0, y = 0) {
        this.__a3fe_x = +x;
        this.__ce97_y = +y;
    }

    get x() { return this.__a3fe_x }
    set x(value) { this.__a3fe_x = +value }

    get y() { return this.__ce97_y }
    set y(value) { this.__ce97_y = +value }

    toString() { return `Point<${ this.__a3fe_x },${ this.__ce97_y }>` }
}
```

The engine would know based on `x` and `y` being declared as a property in the class, and that the method is attached to the class. It would be a static replacement at build time (in babel). Renaming might not be necessary in the actual engine implementation - it could be part of the descriptor.

Keeping `this.x` and `this.y` the same in the code is beneficial because if you decide to make something public you just remove the `-`. This is also consistent with other languages - they just prefix something with `public`/`private`/`protected` and access the property the same way.

**Comment by zenparsing** [comment]
First, private fields are quite different from properties in general.  They are, in effect, the "internal slots" that the ES spec uses to refer to the internal state of built-in objects.  With this proposal, we're trying to allow the JS user to create objects which have their own internal slots.  Importantly, private fields can't be represented as munged property name identifiers.

Second, under your proposal, we would not be able to access the "regular" property "x" on any objects within the class body, which is not quite what we want.

**Comment by lukescott** [comment]
Internal slots can't be represented in ES5 and ES6 (unless I'm missing something?). So properties would have to be used to emulate the feature. An engine doesn't actually have to do it that way.

Here's another idea:

``` javascript
class Point {
    let x
    let y

    constructor(x = 0, y = 0) {
        ::x = +x;
        ::y = +y;
    }

    get x() { return x }
    set x(value) { x = +value }

    get y() { return y }
    set y(value) { y = +value }

    toString() { return `Point<${ x },${ y }>` }
}
```

`let` may not scream private, but it looks like a variable scoped to just the class. Then you just use `x` and `y` without any special syntax. I'm using `::` as a scope resolution operator, which would work if it were freed up by es-function-bind (zenparsing/es-function-bind/issues/18).

Of course I'm looking at the internal slots as if they were part of their own scope. I'm not sure what the ramifications are. My goal with the above is to simplify the syntax and reuse existing terminology (in ES/JavaScript, or otherwise) where possible.

Adding `::` as a scope resolution operator opens a whole new can of worms, but it would be consistent with existing use in other languages.

**Comment by zenparsing** [comment]
What would the semantics of `::identifier` be?  Does that look up `identifier` in an outer scope?

**Comment by lukescott** [comment]
It would be the same as C++ (http://en.wikipedia.org/wiki/Scope_resolution_operator), so yes, `::identifier` would look up `identifier` in an outer scope. This is necessary in constructor since `constructor(x = 0, y = 0)` would shadow `let x`/`let y` defined in the class. The args could use different names, but that could be a bit awkward (coming up with a different name).

For this to work `class` would have to create a scope:

``` javascript
// scope: 0
class Point {
    // scope: 1
    let x
    let y

    constructor(x = 0, y = 0) {
        // scope: 2
        ::x = +x;
        ::y = +y;
    }
// ...
}
```

`::x` and `::y` could be shorthand for `this::x` and `this::y`. Could later be expanded to `super::x` and `super::y`. Unlike C++, `Point::x` and `Point::y` should probably be illegal.

**Comment by lukescott** [comment]
It would also mean that this is possible:

``` javascript
let i = 0;
{
    let i = 1;
    console.log(i); // 1
    console.log(::i); // 0
}
console.log(i); // 0
```

Unless you restrict the syntax to `this::x` and `this::y`. Although having a true scope resolution operator could be useful.

**Comment by lukescott** [comment]
@zenparsing any more feedback on this?

**Comment by zenparsing** [comment]
@lukescott I like the way that you used "let" to suggest an instance variable.  The main problem here is that I think users will want to think of the private field as a _name_, instead of some kind of variable reference.

Honestly, at the moment I'm not very hopeful about the future of private field syntax since decorators have claimed `@`.  The aesthetics are very important to me (and I think important for the success of a feature), and I can't see any way to make the aesthetics work without `@` right now.

Without syntactic support, the best way forward for private state might be to just create an API, using WeakMaps as a basis.

**Comment by domenic** [comment]
I don't think it's all that bad.

``` js
class Point {
  private x, y; // maybe private @x, @y even

  constructor(x, y) {
    this.@x = x;
    this.@y = y;
  }
}
```

**Comment by zloirock** [comment]
@domenic +1

**Comment by PontusHorn** [comment]
Using `let` to define the private fields has its charm as it is a similar concept to an already popular pattern for de facto private variables. I think I prefer `private` though, as this is a different context to where you'd be declaring variables. `private` also has the benefit of filling the same role in many other languages.

As for field access... in other languages I know, there's no special syntax for accessing private fields. Does JavaScript really need one? Why not simply:

``` javascript
class Point {
  private x, y;

  constructor(x, y) {
    this.x = x;
    this.y = y;
  }

  get x() { return this.x; }
}

let p = new Point(5, 5);
console.log(p.x); // 5
console.log(p.y); // undefined
p.x = 10; // TypeError?
console.log(p.x); // 5
```

Admittedly, this doesn't quite fit in with the implementation you suggest if I'm reading it right, but as a developer this is how I'd prefer to use it.

**Comment by lukescott** [comment]
If the class instance had a scope you could simply do `x` and `y`.

**Comment by zenparsing** [comment]
@PontusHorn That doesn't really work in an untyped language like JS.  Consider:

``` js
class A {
    private x = 1;
    static m(a) {
        return a.x;
    }
}

class B {
    constructor() {
        this.x = 2;
    }
}

A.m(new A()); // 1
A.m(new B()); // ??
```

For some given property name "x", we don't know whether to use private lookup or public lookup without type information.

**Comment by zenparsing** [comment]
@domenic If decorators take "@", then that sigil can't really be used for anything else; it would just be too confusing.

Basically, I think decorators need to step aside.  : )

**Comment by kresli** [comment]
what about to use `$` instead of `@`?

**Comment by zloirock** [comment]
@kresli this character allowed in `IdentifierName`. This is valid ES6 + properties initializers syntax:

``` js
class $ { $ = 1; $$(){ this.$ = 2; $$ = 3 } }
```

**Comment by kresli** [comment]
make sense. Then what about `#`? as far I know this is not valid. But maybe I'm wrong.

**Comment by zenparsing** [comment]
@kresli # would work (and some want it) but I find it **so** ugly.  Aesthetics are important too, I think.
