### ISSUE TITLE
Difference from symbols

### ISSUE THREAD

**Issue by RangerMauve** [tc39/proposal-private-fields#13]
As I understand it, the new `Symbol` type can be used to create essentially private variables on an object, having an additional way of having "private variables" on an object seems like it'd be a duplication of functionality.

Could it be possible that the private variable syntax would just be sugar for using symbols?

**Comment by zenparsing** [comment]
Symbols offer collision avoidance but they aren't actually private.
- The symbol-named properties of an object can be inspected with `Object.getOwnPropertySymbols`.
- Symbols can be intercepted with Proxies.

During the ES6 design days, there were attempts to have a "private" version of symbols, but that created all kinds of complications.  This link has some info on why symbols aren't appropriate for privacy.

https://github.com/zenparsing/es-abstract-refs/issues/11

**Comment by RangerMauve** [comment]
Makes sense, thanks for the link.
