### ISSUE TITLE
Would it be possible to omit *this* keywork?

### ISSUE THREAD

**Issue by dfahlander** [tc39/proposal-private-fields#16]
ES6 classes stands compared to other languages with having to write 'this' everywhere to access members. My personal reaction to this is that it bloats the code a bit. Non-prototype pure function-based classes can sometimes be a little prettier in that sense:

``` js
function MyClass () {
    var x; 

    this.getCurrentCount = () => {
        return ++x; // No need to prefix x because this is pure closure, which is nice.
    }
}
```

I think it is a pitty that TC39 didn't go for allowing to omit the _this_ keyword when reading or writing to public properties, (as it works in java and c#), because all ES6 classes are just full of "this" everywhere and it bloats the code. If the reasoning behind it was to require the code be more explicit, I could not agree at all - closures are explicit as they are because there is only one way to resolve them by looking at the scope. And _this_ could be used optionally where required.

But it's obsiously too late to change that now because it would break existing code. So maybe we could put a little hope in private fields instead, allowing the omit of _this_ keywork for private properties, see sample below:

``` js

class MyClass {
    #x = 0;
    returnSomething() {
        return ++#x; // Compiler would be able to resolve count from scope, making *this* optional.
    }
}
```

**Comment by zenparsing** [comment]
Hi @dfahlander, we are definitely considering this.  There are some objections, and it's unclear right now whether those objections will be overcome or not.

**Comment by zenparsing** [comment]
@dfahlander I'm going to close this one.  We'll be revisiting this issue a little further down the road, so stay tuned!
