### ISSUE TITLE
Lexical grammar of PrivateName

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#19]
Should PrivateName be 

```
PrivateName ::
  `#` IdentifierPart
  PrivateName IdentifierPart
```

or 

```
PrivateName ::
  `#` IdentifierName
```

(Well, replace `#` with `@`, if we can...)

The difference is that with the first, you can have things like `#123`.

Another option would be to have `#` as a token by itself, for example:

```
PrivateFieldDefinition :
    `#` IdentifierName Initializer? `;`

MemberExpression :
    MemberExpression `.#` IdentifierName
```

but I've always preferred to think of the entire private name as a single token.

**Comment by littledan** [comment]
I like the single token definition
