### ISSUE TITLE
SyntaxError for duplicate private field definition?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-private-fields#20]
In https://zenparsing.github.io/es-private-fields/#sec-instance-slot-definition , I expected to see a SyntaxError if a private field is defined multiple times. Without that check, the call to [CreateImmutableBinding](http://tc39.github.io/ecma262/#sec-declarative-environment-records-createimmutablebinding-n-s) may hit its internal assertion in step 2.

**Comment by zenparsing** [comment]
Indeed, we're missing the static semantics, one of which would be an early error for that case.

What do you think about making unbound references also a static error?  For example:

``` js
class X {
    constructor() {
        this.#a; // No binding for #a
    }
}
```

It seems like maybe that should be an early error as well.

**Comment by littledan** [comment]
Oh, missed that one. Yeah, good idea to make that an early error. You might also want to consider checking that for references like #a (as opposed to this.#a) that the field exists on the receiver (which I _think_ you could do statically, but it'd take a little bit more infrastructure).

**Comment by zenparsing** [comment]
Duplicate slot definitions are taken care of, created a new issue for the additional early errors.
