### ISSUE TITLE
Editorial suggestions

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-private-fields#21]
- A note explaining that it's OK to put names like "#x" in the same scope, even though they represent objects which aren't exposed to JavaScript, because these are invalid identifiers
- Consider whether it's better to "pollute the internal slot namespace with gensyms" or add a special purpose-built internal slot which associates slotKeys to values (seems like it would mean the same semantics either way, but it feels a little funny).

**Comment by zenparsing** [comment]
Note added.  Second point no longer applies.
