### ISSUE TITLE
Private field declarations need to be in constructor scope

### ISSUE THREAD

**Issue by erights** [tc39/proposal-private-fields#25]
https://github.com/jeffmo/es-class-fields-and-static-properties/issues/2 applies here as well. Notice the existing notational redundancy in examples such as

``` js
class Point {
    #x;
    #y;
    constructor(x = 0, y = 0) {
        this.#x = +x;
        this.#y = +y;
    }
}
```

If the two lines in the constructor were written using some declare-and-initialize syntax distinct from assignment, then these two lines would be all that is necessary to declare and initialize both of these private fields in a data-dependent way. As with https://github.com/jeffmo/es-class-fields-and-static-properties/issues/2 , this would smoothly accommodate future support for const private fields, which must be initialized and cannot be assigned.

**Comment by erights** [comment]
Adapting the notation from https://github.com/wycats/javascript-private-state/issues/11 to this proposal, the syntax for the above example would be

``` js
class Point {
    constructor(x = 0, y = 0) {
        private #x = +x;
        private #y = +y;
    }
}
```

**Comment by zenparsing** [comment]
I think we've reached agreement on the location of the definitions within the class body braces.
