### ISSUE TITLE
Why we don't need help reifying the private field name

### ISSUE THREAD

**Issue by erights** [tc39/proposal-private-fields#26]
This is more recording an observation than filing an issue, so I'll close it immediately. If there is an actual open issue here, feel free to reopen. Observation mostly from @zenparsing  during a conversation we had at the last tc39 mtg. Any errors are mine.
## Historical note

The committee first tried to support private state by inventing a notion of private symbols (aka "private names"). These private symbols would be a reified name of private properties in a sense analogous to how regular symbols are reified names of regular symbol-named properties. However, this failed because it was impossible, with this reification, to reconcile secure encapsulation with transparency across membranes. (See https://github.com/zenparsing/es-abstract-refs/issues/11#issuecomment-65723350 )

From this conflict rose two schools, which I will call the "private field camp" (primarily @zenparsing and myself) and the "private slot camp" (primarily @allenwb and @rossberg). The private field camp used WeakMaps in much the same way this one does. But these WeakMaps were reifiable, which led to conflict with the "private slot camp" that thought of these slots in a more static sense. The names of these slots were no longer reified, but were discussed in terms of unobservable "private symbols". 

We all realized that, by making the WeakMaps unreified, as in the current proposal, that the proposals of the two camps because equivalent. (The subsequent divergence of https://github.com/zenparsing/es-private-fields vs https://github.com/wycats/javascript-private-state is for mostly orthogonal reasons.) From at least my point of view, we were only postponing the reification to get agreement. Once we had such private state, the needs for reification, such as to support friendship, combined with the constraints of secure encapsulation and transparency across membranes, would push us towards the postponed reification of private field names as something very WeakMap-like,
## The Insight

At the 1/2016 tc39 mtg, @zenparsing mentioned to me over dinner that, given only unreified private state and no WeakMaps anywhere, one could build a WeakMap-like abstraction. ( @zenparsing could you post the code for that? ) Whether via a complete reification of these names as a WeakMap-like abstraction, or a lightweight reification as shown at https://github.com/zenparsing/es-private-fields/issues/7#issuecomment-123530628 (recorded by @zenparsing as attributed to @allenwb)

``` js
let getX, setX;

class X {
    #x;
    static {
        getX = (obj) => obj.#x;
        setX = (obj, val) => obj.#x = val;
    }
}
```

[updated to modern proposal by changing at-sign to pound-sign] 

any such reification already has the behavior that we were originally seeking from the WeakMap reification of private names: they maintain secure encapsulation while being transparent across membranes. They do both for the same reason: If Alice, on one side of a membrane, tries to use this reification through a membrane boundary, then the faulting is on the name side, not on the state-bearing-object side.

``` js
setXProxy(anXProxy, value)
```

faults on `setXProxy`, giving it control and access to `anXProxy`, rather than faulting on `anXProxy` and giving it control and access to `setXProxy`.

Whether we want to better support this pattern or provide sugar for it in the future is another matter. But the fundamentals are already right and do not need any additional mechanism.

**Comment by erights** [comment]
Genuine WeakMaps should be implemented
- using the transposed representation, where value is hung off the key, as looked up by the map identity
- falling back to ephemeron collection if necessary to collect unreachable values.

Currently, all browsers fail one of these two criteria. Edge implements the transposed representation, which is great, but does not fall back to ephemeron collection to clean up values that would be looked up by map identities that are already collected.

All other browsers do use ephemeron collection when needed, but do not use the transposed representation.

From early on, we realized that the use of WeakMaps for class-private state only needed the transposed representation. **Given the transposed representation**, full ephemeron collection was irrelevant for this use-case, since the instance (key) holds onto its class, which holds only the WeakMaps naming that class' private instance state. Thus, the lifetime of the keys of these WeakMaps -- the instances of these classes -- cannot exceed the lifetimes of these WeakMaps themselves.

Given the expected implementation of private state, the above userland reification technique already gives us the transposed representation without ephemeron collection with no further implementation work by anyone. On browsers not implementing the transposed representation for their official WeakMaps, userland WeakMap emulations via private state will often outperform the builtin WeakMaps. Though, like current Edge, any such emulation will also fail to provide full ephemeron collection.

**Comment by erights** [comment]
Per the opening comment, closing for now. Please reopen if appropriate.

**Comment by zenparsing** [comment]
Here is the implementation of a WeakMap-like abstraction using private fields:

``` js
const DELETED_TOKEN = {};

/*

A map class, implemented with private slots, which has the following properties:

- The presence of a mapping k => v in a PFMap does not by itself make k or v reachable
- For each mapping k => v in a PFMap m (whether m is reachable or not), if k is reachable then v is reachable

*/
class PFMap {

    #ctor;

    constructor() {

        this.#ctor = class extends function(obj) { return obj; } {

            #slot;

            constructor(key, value) { 
                super(key); 
                this.#slot = value;
            }

            static get(key) {
                try { 
                    const value = key.#slot; 
                    if (value !== DELETED_TOKEN)
                        return value;
                } catch (x) {}

                return undefined;
            }

            static set(key, value) {
                try { key.#slot = value; }
                catch (x) { new this(key, value); }
            }

            static has(key) {
                try { return key.#slot !== DELETED_TOKEN; }
                catch (x) { return false; }
            }

            static delete(key) {
                try { 
                    if (key.#slot !== DELETED_TOKEN) {
                        key.#slot = DELETED_TOKEN; 
                        return true;
                    }
                } catch (x) {}

                return false;
            }

        };

    }

    get(key) {
        return this.#ctor.get(key, value);
    }

    set(key, value) {
        return this.#ctor.set(key, value), this;
    }

    delete(key) {
        return this.#ctor.delete(key);
    }

    has(key) {
        return this.#ctor.has(key);
    }

}
```

**Comment by littledan** [comment]
Note that, with the private state proposal in this repository, I'd expect realistic implementations to have different garbage collection behavior on WeakMaps vs this implementation. For normal WeakMaps, the WeakMap may be collected if there is no reference to it aside from having objects as keys. However, for private state, an implementation might keep the private state field alive even if no methods are alive anymore that refer to it, if an instance is alive. However, the spec does not define GC or liveness, so this distinction does not exist in spec-land.

@allenwb, what are your thoughts on this proposal, given the rationale for unification from @erights ?
