### ISSUE TITLE
What stage is this proposal at?

### ISSUE THREAD

**Issue by erights** [tc39/proposal-private-fields#27]
I don't see it on the table at https://github.com/tc39/ecma262 nor at https://github.com/tc39/ecma262/blob/master/stage0.md . Depending on the state it is at, it should be in one of these two places.

**Comment by zenparsing** [comment]
I should have put it into the stage 0 document after the Paris meeting last year, but now we have the forking issue with Allen's proposal.  Regardless, I'll go ahead and submit a pull request to get it on the stage 0 doc.

**Comment by zenparsing** [comment]
Stage 1!
