### ISSUE TITLE
Migrate to github.com/tc39?

### ISSUE THREAD

**Issue by erights** [tc39/proposal-private-fields#28]
Though I cannot find it right now, on WeakRefs https://github.com/tc39/proposal-weakrefs I remember the question came up about whether it is too early for us to have posted it on the github.com/tc39 site, vs waiting for some future stage before migrating. IIRC @allenwb commented that, since it is already under active discussion by the committee, it help ECMA's record keeping duties for the repo to already be there. As a result of this comment, we did not migrate WeakRefs off that site while waiting for stage promotion.

I suggest the same applies here.

**Comment by zenparsing** [comment]
That would be fine with me, but we certainly only want either this repository or that other one : ), and not both.  I think we should endeavor to resolve the forking problem at the next meeting, and then move this into tc39 at that point.

**Comment by zenparsing** [comment]
I've requested a transfer to tc39 via @bterlson
