### ISSUE TITLE
Add shorthand syntax

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#29]
Add _PrivateName_ as a primary expression, which desugars to `this.#name`.

**Comment by rauschma** [comment]
Thanks for this proposal!

I’ve always liked the explicitness of having to prefix `this.` in JavaScript (I’m saying this as someone who has written lots of Java where you don’t have to do that).

If you do this, you should probably introduce a keyword for declaring private fields (I’m wondering whether you shouldn’t do so, either way – it’s how all other declarations work in JS):

``` js
class Point {

    private #x;
    private #y;

    constructor(x = 0, y = 0) {
        this.#x = +x;
        this.#y = +y;
    }
}
```

**Comment by pitaj** [comment]
So you're saying I could do this:

``` js
class Point {
  #x;
  #y;

  constructor(x = 0, y = 0) {
    #x = +x;
    #y = +y;
  }
}
```

Instead of this:

``` js
class Point {
  #x;
  #y;

  constructor(x = 0, y = 0) {
    this.#x = +x;
    this.#y = +y;
  }
}
```

**Comment by austinkelleher** [comment]
@zenparsing can you give a code example? I am curious.

**Comment by littledan** [comment]
The shorthand syntax is in the current spec draft and explainer.
