### ISSUE TITLE
Make initialization transactional

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#3]
If the evaluation of any initializer results in an abrupt completion, then initialization for all fields should fail.  The object should not be left in a state where some private fields are initializes and some are not.

**Comment by erights** [comment]
This was closed with what resolution? Why?

**Comment by zenparsing** [comment]
I originally wanted it to be the case that if any field initializer should fail, then all private fields for that class definition would be "uninitialized", so that the super constructor couldn't leak instances with partially initialized fields.

I gave up on that goal because it seemed unnecessarily complicated.  Instead, the current draft simply guarantees that all private fields are initialized to undefined before any code runs which may result in an exception.  See https://zenparsing.github.io/es-private-fields/#sec-intiializeprivatefields, step 7.

That gives us the main property that I was after, namely that an object either has all the fields defined by a given class, or none.
