### ISSUE TITLE
Separate definition of members with different access level

### ISSUE THREAD

**Issue by ghost** [tc39/proposal-private-fields#31]
My proposal includes some another changes of ecma such as extension of class. Maybe you can figure out more simple way for that. 

Mix fields with different access level aren't good for clear understanding. I want to be able to distinguish the definition of private fields (like we can do it at ruby, swift etc.).

``` javascript
class A {}

#extension class A {
    func() {}
}
```

**Comment by zenparsing** [comment]
Closing as off-topic since this proposal isn't about extension methods.
