### ISSUE TITLE
I'm sorry, but I do not know where else to write. (Close this ticket)

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [tc39/proposal-private-fields#43]
I want to propose to the standard things like audience INTERNAL objects events. Tell me where I should write about it?

``` javascript
var obj = {}
Object.addCoreEventListener(obj, 'destroy', function(obj){
 // call this function before javascript core destroy this object from memory
})
```

Tell me where I should write about it?

**Comment by bterlson** [comment]
See here: https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md. In short, [es-discuss](http://esdiscuss.org/)
