### ISSUE TITLE
Prohibiting duplicate fields

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-private-fields#48]
Currently it's a runtime error (see [3.1.4.d.ii](https://tc39.github.io/proposal-private-fields/#sec-intiializeprivatefields)) to instantiate a class which contains a duplicate private field, like `class { #a; #a; }`.

It could instead and more usefully be an early error, or at the very least an error at class definition time instead of at class instantiation.

**Comment by zenparsing** [comment]
I agree an early error would be most useful here.
