### ISSUE TITLE
Shortcutting Private Access Allowed?

### ISSUE THREAD

**Issue by eggers** [tc39/proposal-private-fields#51]
What should/does happen if you do something like this:

``` js
x.shortcutAccessToPrivateField = function() {
  return this.#privateField;
}
```

**Comment by zenparsing** [comment]
`#privateField` does not exist in the lexical scope and therefore it produces an error (perhaps a compile-time error).

**Comment by littledan** [comment]
Thanks for the explanation @zenparsing ; looks like we don't have to discuss anything more here.
