### ISSUE TITLE
Develop vision for new object model

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#6]
The basic underlying idea is that:
1. All per-object state is stored in instance variables (i.e. private fields).  Instances cannot have JS object properties.
2. The external interface is defined by the object's prototype chain.
3. The prototype link is immutable for all objects.
4. All object properties are non-configurable, non-writable.

**Comment by zenparsing** [comment]
This is basically `const class C {}`

**Comment by zenparsing** [comment]
We should create a new repository for developing const classes.  For reference, I'm currently thinking that const classes should have the following semantics:
- Declarations create const bindings.
- They can only extend other `const` classes.
  - Collary:  They do not have `Object.prototype` on their prototype chain.
- Their prototype object is frozen.
- Instances are frozen:  they cannot have _any own properties_ (although they may have private fields).
- The [Prototype] of instances is immutable.
- The [Prototype] of the constructor is immutable.

I'm unsure whether constructor itself should be frozen.

**Comment by zenparsing** [comment]
Also
- `const` class constructors may not return anything other than undefined.

**Comment by zenparsing** [comment]
@erights Do you think that for const classes, the constructor itself should be frozen?

Also, any comments on the list above?  The restriction on instances having _any_ own properties is pretty radical, but I think it's also essential to the idea.

**Comment by zenparsing** [comment]
What if you want to split a class definition among several different files?

**Comment by erights** [comment]
I'll answer one point at a time.

> The basic underlying idea is that:
> 1. All per-object state is stored in instance variables (i.e. private fields). Instances cannot have JS object properties.
> 2. The external interface is defined by the object's prototype chain.
> 3. The prototype link is immutable for all objects.
> 4. All object properties are non-configurable, non-writable.

Doesn't (4) conflict with (1)? What properties does (4) refer to?

Why do we need restriction (1)?

**Comment by erights** [comment]
> We should create a new repository for developing const classes. 

Good.

> For reference, I'm currently thinking that const classes should have the following semantics:
> - Declarations create const bindings.
> - They can only extend other const classes.
>   - Collary: They do not have Object.prototype on their prototype chain.

Why do we need the above restriction? In particular, in a SES environment, we freeze the real Object.prototype, satisfying the next condition.

> - Their prototype object is frozen.

So perhaps extend this condition to say that the entire inheritance chain must be frozen, and drop the first two restrictions?

> - Instances are frozen: they cannot have any own properties (although they may have private fields).

I don't yet understand the motivation for no own properties.

> - The [Prototype] of instances is immutable.
> - The [Prototype] of the constructor is immutable.
> 
> I'm unsure whether constructor itself should be frozen.

Yes. I don't think the const class itself should have any reachable mutable state other than what is provided by the API it defines.

**Comment by erights** [comment]
I agree with all the restrictions above that I did not comment on.

> What if you want to split a class definition among several different files?

Neither non-const classes nor IIUC modules allow this split, so why should const classes?

**Comment by zenparsing** [comment]
> So perhaps extend this condition to say that the entire inheritance chain must be frozen, 
> and drop the first two restrictions?

That would be fine.

Still, we need to decide whether the following:

``` js
const class C {}
```

extends Object or not.  The options seem to be:
1.  It does not.  That would create a striking dissimilarity from non-const classes.
2.  It does, but throws a runtime error if Object.prototype is not frozen.

Neither option seems great, but as Object.prototype is pretty useless anyway...

> I don't yet understand the motivation for no own properties.

Completely understandable.  : )

This idea came from a vision-of-sorts that I had at the last meeting.  If all state is stored in private fields and the only interface the object has is granted by it's (frozen) prototype chain, then those objects can be implemented with the same internal representation as Java objects.

This is pretty much exactly where Andreas wants to go with "strong" classes.  Except instead of private fields, he seals the object after the constructor has run and severely limits where you can use "this" inside of the constructor.

Another aspect of "strong" objects is that any "get" for a property not defined on the object (or its prototype chain) results in a TypeError.  Well, this is exactly the behavior that we have for private fields.  In fact, I would say that objects created from "const classes" (as defined above) _are_ strong objects.  And if so, then that might mean that we don't need a "strong" mode.

It's a bit radical, though I admit.

**Comment by zenparsing** [comment]
And it's not a fully baked thing.

So I think we should leave off that requirement for now.

**Comment by erights** [comment]
Good question about 

```
const class C {}
```

I feel conflicted about it.  Altogether, I think I favor (1)

OTOH, if Object.prototype, Object, and Function.prototype are all frozen, then

```
const class C extends Object {}
```

should work fine.

**Comment by erights** [comment]
> We should create a new repository for developing const classes.

I still emphatically agree! Is there one? Where?

**Comment by zenparsing** [comment]
There is not!  But I will create one in the next few days and ping you.
