### ISSUE TITLE
Friendship patterns

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#7]
Since instance variables are lexically confined, how can we implement friendship patterns?  Let's use this issue to collect some ideas.

**Comment by zenparsing** [comment]
In this example, the class that is granting access provides a one-time-use class method which returns a private state access capability:

``` js
let EXPOSE = Symbol();

class HasPrivate {

    @x;

    static [EXPOSE]() {

        // Only allow the first caller to get anything useful
        if (!EXPOSE)
            return {};

        EXPOSE = null;

        // Return an object which can access the instance variable
        return { 
            getX(obj) { return obj.@x }
        };
    }
}

const fieldAccessor = HasPrivate[EXPOSE]();

class UsesPrivate {

    constructor(hasPrivate) {

        let x = fieldAccessor.getX(hasPrivate);
    }
}
```

**Comment by zenparsing** [comment]
Another strategy for granting friend access might be decorators.  If a decorator is applied to a private field, then _maybe_ that means that a read/write capability is provided to the decorating function as argument.  I haven't fully thought this through.

**Comment by domenic** [comment]
This seems a bit disappointing. `Object.getOwnPropertySymbols(HasPrivate)` still shows something.

I'd really want something more like this "private symbol" solution:

``` js
const s = new PrivateSymbol();

function canAcceptFoosOrBars(x) {
  if (!x[s]) {
    throw new TypeError("Must support the foobar protocol");
  }

  // ...
}

class Foo {
  constructor() {
    this[s] = true;
  }
}

class Bar {
  constructor() {
    this[s] = true;
  }
}
```

**Comment by domenic** [comment]
I guess your solution can be patched with `delete this[EXPOSE]` before `EXPOSE = null`. Maybe that's good enough.

**Comment by zenparsing** [comment]
I think we mentioned this at the meeting, but decorators might be a nice solution here.  If the decorator, when applied to a private field, receives an "accessor-ish" property-descriptor-ish object, we could use that to expose the capability outside of the class body.

Something like:

``` js
function expose(to) { 
    return (proto, name, desc) => {
        // Reveal a "private map"
        to[name] = {
            get(obj) { return desc.get.call(obj) },
            set(obj, val) { desc.set.call(obj, val) },
        };
    };
}

const friend = {};

class C {
    #expose(friend) // A hypothetical decorator
    @x; 
}

function getXFromOutside(obj) {
    return friend["@x"].get(obj);
}

```

**Comment by bergus** [comment]
Does "friendship" include inheritance, for "protected" properties and the like?

**Comment by zenparsing** [comment]
@bergus By "friendship" I mean exporting the capability to get or set a private field value of an arbitrary object outside of the lexical context of the class in general.

Protected fields won't be a part of this proposal, although I'd like to leave open the possibility.

**Comment by zenparsing** [comment]
Allen came up with the possibility of using a "static" initialization block for this purpose:

``` js
let getX, setX;

class X {
    @x;
    static {
        getX = (obj) => obj.@x;
        setX = (obj, val) => obj.@x = val;
    }
}
```

I think this actually works out quite well.
