### ISSUE TITLE
Private fields seem not so private

### ISSUE THREAD

**Issue by AbrahamTewa** [tc39/proposal-private-fields#70]
Hi,

I don't understand how theses properties are realy private ? I mean, it's easy to do something like that :

`MyLibrary.js` :
``` javascript
// MyLibrary.js

class MyClass {
   #x;

   constructor(value) {
      this.#x = value;
   }

} 
```

```javascript
// RogueLibrary.js

MyClass.prototype.getX = function getX() {
   return this.#x;
}

MyClass.prototype.setX = function setX(value) {
   this.#x = value;
}
```

Because we can access the prototype of a class, it's easy to alter it and expose private properties.

**Comment by zenparsing** [comment]
HI @AbrahamTewa , the private field declarations are lexically scoped, similar to variable declarations. The names aren't in scope outside of the class where they are defined. See #65 for a similar question.
