### ISSUE TITLE
Nominal type checking and private state across realms

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#9]
Any "duplicated" class definition (whether different URLs, different versions of the same library, or code loaded into different realms) will be seen by the system as different nominal types, and hence independent with respect to private state.

This is going to be true for any private state strategy (including WeakMaps and private symbols).  We need to explore this.

**Comment by erights** [comment]
This is not just duplicated code. Classes are generative.

``` js
function fooMaker() {
  class Foo {
    #x;
    constructor(x) { #x = x; }
    add(aFoo) { return #x + aFoo.#x; }
  }
  return Foo;
}

const Foo1 = fooMaker();
const f1 = new Foo1(8);
const Foo2 = fooMaker();
const f2 = new Foo2(9);
f1.add(f2);  // throws
```

That last statement throws because f1 and f2 are instances of different classes, even though they are instances of the same non-duplicated class code.

**Comment by zenparsing** [comment]
Indeed.  I'm (perhaps irrationally) worried that as programmers start to use private fields, they'll run into little things like this, particularly because JS users have to deal with cross-realm programming and library dependency duplication.
