### ISSUE TITLE
can we just use private keyword?

### ISSUE THREAD

**Issue by zh99998** [tc39/proposal-private-fields#92]
`#` is very ugly.. and looks like comment, may confused
`#` for comment is widely use in many language including coffeescript.

**Comment by bakkot** [comment]
Duplicate of https://github.com/tc39/proposal-private-fields/issues/14.

See [the FAQ](https://github.com/tc39/proposal-private-fields/blob/master/FAQ.md#why-arent-declarations-private-x).
