### ISSUE TITLE
Proposal status is unclear

### ISSUE THREAD

**Issue by rictic** [tc39/proposal-private-fields#97]
I don't see this proposal listed at https://github.com/tc39/proposals or https://prop-tc39.now.sh/ but it seems active and fairly well developed. Are those lists incomplete, or is perhaps this proposal listed under a grouping of related proposals?

**Comment by bakkot** [comment]
It's now a part of the [class fields proposal](https://github.com/tc39/proposal-class-fields).

That should probably be mentioned somewhere.
